name: radar
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.5
  - cycler=0.10.0
  - dbus=1.13.0
  - decorator=4.3.2
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.9.1
  - future=0.17.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - jpeg=9c
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.36
  - libstdcxx-ng=7.3.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.3.0
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - obspy=1.1.0
  - openssl=1.0.2p
  - pandas=0.24.0
  - pcre=8.41
  - pip=19.0.1
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - pysocks=1.6.8
  - python=3.7.0
  - python-dateutil=2.7.5
  - pytz=2018.9
  - qt=5.6.2
  - readline=7.0
  - requests=2.21.0
  - setuptools=40.7.1
  - sip=4.18.1
  - six=1.12.0
  - sqlalchemy=1.2.17
  - sqlite=3.26.0
  - tk=8.6.9
  - tornado=5.1.1
  - urllib3=1.24.1
  - wheel=0.32.3
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11
  - blas=1.0
  - intel-openmp=2019.1
  - mkl=2019.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - scipy=1.2.0
  - pip:
    - geographiclib==1.49
    - geopy==1.18.1
    - pynmea2==1.12.0
    - readgssi
