name: radar
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pip
  - pip:
    - geographiclib==1.49
    - geopy==1.18.1
    - pynmea2==1.12.0
    - git+https://github.com/iannesbitt/readgssi.git#egg=readgssi
